// <auto-generated />
using System;
using BackendTZ.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendTZ.DataAccess.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20240911170541_addPrimaryKey")]
    partial class addPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendTZ.DataAccess.Entities.BookingEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConferenceHallId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ConferenceHallId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("BackendTZ.DataAccess.Entities.ConferenceHallEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BaseRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Halls", t =>
                        {
                            t.HasCheckConstraint("CK_ConferenceHall_Capacity", "[Capacity]<= 1250");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("754790f9-7655-4548-b9ef-329503293043"),
                            BaseRate = 2000m,
                            Capacity = 50,
                            Name = "Зал А"
                        },
                        new
                        {
                            Id = new Guid("33b9677f-d265-4233-80ad-424d004c60ce"),
                            BaseRate = 3500m,
                            Capacity = 100,
                            Name = "Зал B"
                        },
                        new
                        {
                            Id = new Guid("c8889cfe-e315-44f9-8924-e13633382b15"),
                            BaseRate = 1500m,
                            Capacity = 30,
                            Name = "Зал C"
                        });
                });

            modelBuilder.Entity("BackendTZ.DataAccess.Entities.ServiceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = new Guid("24970e38-c963-4612-90f7-404a931ac66e"),
                            Name = "Проєктор",
                            Price = 500m
                        },
                        new
                        {
                            Id = new Guid("b37ddcb1-325b-4a0e-b667-051be081b4c3"),
                            Name = "Wi-Fi",
                            Price = 300m
                        },
                        new
                        {
                            Id = new Guid("3c506468-23bb-43a9-9291-5b01b03b0613"),
                            Name = "Звук",
                            Price = 700m
                        });
                });

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.Property<Guid>("BookingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BookingsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("BookingEntityServiceEntity");
                });

            modelBuilder.Entity("ConferenceHallEntityServiceEntity", b =>
                {
                    b.Property<Guid>("ConferenceHallsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ServicesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConferenceHallsId", "ServicesId");

                    b.HasIndex("ServicesId");

                    b.ToTable("ConferenceHallEntityServiceEntity");
                });

            modelBuilder.Entity("BackendTZ.DataAccess.Entities.BookingEntity", b =>
                {
                    b.HasOne("BackendTZ.DataAccess.Entities.ConferenceHallEntity", "ConferenceHall")
                        .WithMany()
                        .HasForeignKey("ConferenceHallId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConferenceHall");
                });

            modelBuilder.Entity("BookingEntityServiceEntity", b =>
                {
                    b.HasOne("BackendTZ.DataAccess.Entities.BookingEntity", null)
                        .WithMany()
                        .HasForeignKey("BookingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTZ.DataAccess.Entities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceHallEntityServiceEntity", b =>
                {
                    b.HasOne("BackendTZ.DataAccess.Entities.ConferenceHallEntity", null)
                        .WithMany()
                        .HasForeignKey("ConferenceHallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendTZ.DataAccess.Entities.ServiceEntity", null)
                        .WithMany()
                        .HasForeignKey("ServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
